spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:file:~/avaliacao4
        username: a4
        password:
        driverClassName: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
